## MySQL DataSource
spring:
  datasource:
    url: jdbc:mysql:///main-db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    
#`hibernate_sequence' doesn't exist
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      
# drop n create table, good for testing, comment this in production
      ddl-auto: validate