spring:
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///main-db
    #url: jdbc:mysql:///techouts
    username: root
    password: root
    
  mail:
    host: smtp.gmail.com
    port: 587
    username: shubhamsahoo19981@gmail.com
    password: mrshubhamji
    properties:
      mail: 
        smtp:
          port: 25
          auth: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
          starttls:
            enable: true